site_name: "ALICE software"
repo_name: View source code
repo_url: https://github.com/alisw/alisw.github.io

theme:
  name: material
  logo: alice_logo.png
  features:
    - content.code.copy

extra_css: [stylesheets/extra.css]

use_directory_urls: true # Required for backwards compatibility with some old URLs

nav:
- Home: index.md
- Basic tutorial: git-tutorial.md
- Advanced tutorial: git-advanced.md
- Build infrastructure: infrastructure.md
- Tasks:
  - Release process of AliRoot / AliPhysics: infrastructure-release-process.md
  - Release process O2PDPSuite: infrastructure-release-process-o2.md
  - O2 stable branches: infrastructure-o2-branches.md
  - Nightly builds: infrastructure-nightly.md
  - CVMFS releases: infrastructure-cvmfs.md
  - Testing of Pull Requests (continuous integration): infrastructure-pr-testing.md
  - Build Logs: infrastructure-logs.md
  - Release Publishing: infrastructure-publisher.md
  - Release and Validation: infrastructure-relval.md
  - AliBI User Guide: infrastructure-alibi-user-guide.md
  - Setting up automatic release builds: infrastructure-auto-builds.md
  - Generation of RPMs: infrastructure-rpms.md
  - Known tradeoffs: infrastructure-known-tradeoffs.md
  - Building Docker images with Packer: infrastructure-docker-packer.md
- Infrastructure details:
  - Using Nomad, Consul and Vault: infrastructure-nomad.md
  - Nomad cluster setup: infrastructure-nomad-host.md
  - MacOS builder setup: infrastructure-macos.md
  - Virtual and physical machines: infrastructure-machines.md
  - AliEn VoBox: infrastructure-alienvobox.md
  - Web Frontend: infrastructure-frontend.md
  - Jenkins: infrastructure-jenkins.md
  - AliBuild S3 Repository: infrastructure-repository.md
  - AliBI: infrastructure-alibi.md
  - Setting up automatic release builds: infrastructure-auto-builds.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: "#"
