site_name: "ALICE software"
repo_name: View source code
repo_url: https://github.com/alisw/alisw.github.io

theme:
  name: material
  logo: alice_logo.png

extra_css: [stylesheets/extra.css]

use_directory_urls: true # Required for backwards compatibility with some old URLs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: "#"
